### ISSUE TITLE
coffeescript?

### ISSUE THREAD

**Issue by mark-hahn** [coreh-deprecated/nide#21]
coffeescript?

**Comment by coreh** [comment]
Huh?

Nide already supports the editing of CoffeeScript files. (with Syntax Highlighting)

Are you asking about a specific feature? Or are you having problems editing coffeescript?

**Comment by mark-hahn** [comment]
Great!  (Sorry about the cryptic post).

I looked and couldn't find any mention of CS.  Are there docs or should I just download it and try it?

**Comment by coreh** [comment]
Unfortunately, there isn't (yet) much documentation beyond what's on the main website. (Like a list of all supported languages.) 

We used to have an online installation ready for people to try out nide, but since it was hosted on the Node Knockout server, and the competition is over, it's no longer available.

If you're on a UNIX system (like OS X or Linux), just give it a try via NPM. Windows support might still take some time...
