### ISSUE TITLE
File not added to project on Windows

### ISSUE THREAD

**Issue by gfosco** [coreh-deprecated/nide#29]
I created a project, created a new file underneath, edited it quite a bit... The file was definitely saved and updated continuously on disk.  No package.json was created.  I installed a NPM module and that worked correctly.  (though no node_modules folder was created, so it must have been installed globally?)

I stopped the Nide process and restarted it.  The project appears empty.

**Comment by coreh** [comment]
That might be an issue with the file listing library we're using. (`dive`)

Windows support is planned, but it might take a while (due to the differences between UNIX and Windows, my general ignorance of how Windows handles things, and since I don't currently have access to a Windows machine for development.)

Since this bug is somewhat a subset of bug #6, I'm going to close this one and copy your post there. Is that ok?

**Comment by gfosco** [comment]
Sure.
On Dec 31, 2011 1:51 PM, "Marco Aurlio" <
reply@reply.github.com>
wrote:
