### ISSUE TITLE
Error when installing with npm

### ISSUE THREAD

**Issue by AlbertoElias** [coreh-deprecated/nide#3]
When I run sudo npm install -g nide I get the following error:

npm WARN Invalid range in engines.node.  Please see `npm help json` ~v0.4.9
npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: nide@0.1.0
npm ERR! Required: {"node":"~v0.4.9"}
npm ERR! Actual:   {"npm":"1.0.15","node":"v0.4.9"}
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/Users/aeliasnet/local/bin/npm" "install" "-g" "nide"
npm ERR! cwd /Users/aeliasnet
npm ERR! node -v v0.4.9
npm ERR! npm -v 1.0.15
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/aeliasnet/npm-debug.log
npm not ok

I remember having this same error in my node.js project and fixed it by changing "node": "v0.4.9" without the ~. I don't know why it occurs though...

**Comment by coreh** [comment]
Hey, misfo pointed out on issue #4 that I should be using either "v0.4.9" or "~0.4.9", but not both at the same time. 

I have already merged the fix, but I'm not making a new release on NPM until Node KO ends (September 6) because that would be against the rules. Until then, you can clone the repository and use npm to install nide directly from the folder. (npm install ./folder-name). I hope you understand.

Marking this as closed for now.
